### ISSUE TITLE
module yealinkrom missing

### ISSUE THREAD

**Issue by johnkeates** [synacktiv/yealink_tools#2]
I looks like there is a missing module, it doesn't seem to be published anywhere either. Is this because it needs to be generated from Kaitai?

**Comment by johnkeates** [comment]
It was just simple struct generation from kaitai.

**Comment by serdeliuk** [comment]
> It was just simple struct generation from kaitai.

Hi, how did you generated the missing module? Thanks in advance.

**Comment by johnkeates** [comment]
You can generate it using kaitai.  https://github.com/synacktiv/yealink_tools/blob/513308d2be9beeef4298fe41743605208e16a436/yealink_rom_dump.py#L7
